# Backpropagation Algorithm

We will implement the following neural network.

![backpropagation](images/backpropagation.PNG)

## Chain Rule Tree Diagram

Open the following image in full view.

![chain_rule_tree_diagram](./images/chain_rule_tree_diagram.PNG)

Mean squared error:

$$
\begin{align*}
    MSE &= \frac{1}{2} \sum^{1}_{n=0} (t_i - y_i)^2 \\
    &= \frac{1}{2} (t_0 - y_0)^2 + \frac{1}{2} (t_1 - y_1)^2
\end{align*}
$$

In general:
$$
\begin{align*}
    \frac{\partial MSE}{\partial y_{i}} &= -(t_i - y_i) \\
    &= y_i - t_i 
\end{align*}
$$

In specific case:
$$
\begin{align*}
    \frac{\partial MSE}{\partial y_{0}} &= -(t_0 - y_0) \\
    &= y_0 - t_0 
\end{align*}
$$

$$
\begin{align*}
    \frac{\partial MSE}{\partial y_{1}} &= -(t_1 - y_1) \\
    &= y_1 - t_1 
\end{align*}
$$

Linear activation (before final output):
$$
\begin{align*}
    y_i &= z_i^{(L)}
    \hspace{35pt}
    where
    \hspace{10pt}
    \{0, 1, ..., l, ..., L-1, L\} \,\, layers
\end{align*}
$$

In general:
$$
\begin{align*}
    \frac{\partial y_i}{\partial z^{(L)}_{i}} &= \frac{\partial a^{(L)}_i}{\partial z^{(L)}_{i}} = 1 \\
\end{align*}
$$

In specific case:
$$
\begin{align*}
    \frac{\partial y_0}{\partial z^{(L)}_{0}} &= \frac{\partial a^{(L)}_0}{\partial z^{(L)}_{i}} = 1 \\
\end{align*}
$$

$$
\begin{align*}
    \frac{\partial y_1}{\partial z^{(L)}_{1}} &= \frac{\partial a^{(L)}_1}{\partial z^{(L)}_{i}} = 1 \\
\end{align*}
$$

Before activation function:

- In matrix form:
$$
\begin{align*}
    z^{(l)} &= W^{(l)}_{*} \, a^{(l-1)}_{*} + b^{l} \\
    &= W^{(l)} \, a^{l-1}
\end{align*}
$$

Note that with a trick we can write:
$$
\begin{align*}
    z^{(l)} &= W^{(l)}_{*} \, a^{l-1}_{*} + b^{l}
    \hspace{35pt}
    where
    \hspace{10pt}
    W^{(l)} \in \mathbb{R}^{M \, x \, N}, a^{(l-1)} \in \mathbb{R}^{N}, b^{(l)} \in \mathbb{R}^{M} \\
    %
    &=
    \begin{bmatrix}
        w^{(l)}_{00} & w^{(l)}_{01} & \dots & w^{(l)}_{0N} \\
        w^{(l)}_{10} & w^{(l)}_{11} & \dots & w^{(l)}_{1N} \\
        \vdots & \vdots & & \vdots \\
        w^{(l)}_{M0} & w^{(l)}_{M1} & \dots & w^{(l)}_{MN}
    \end{bmatrix}
    %
    \begin{bmatrix}
        a^{(l-1)}_{0} \\
        a^{(l-1)}_{1} \\
        \vdots \\
        a^{(l-1)}_{N}
    \end{bmatrix}
    %
    +
    \begin{bmatrix}
        b^{(l)}_{0} \\
        b^{(l)}_{1} \\
        \vdots \\
        b^{(l)}_{M}
    \end{bmatrix} \\
    % 
    &=
    \begin{bmatrix}
        w^{(l)}_{00} a^{(l-1)}_{0} + w^{(l)}_{01} a^{(l-1)}_{1} + \dots + w^{(l)}_{0N} a^{(l-1)}_{N} \\
        w^{(l)}_{10} a^{(l-1)}_{0} + w^{(l)}_{11} a^{(l-1)}_{1} + \dots + w^{(l)}_{1N} a^{(l-1)}_{N} \\
        \vdots \\
        w^{(l)}_{M0} a^{(l-1)}_{0} + w^{(l)}_{M1} a^{(l-1)}_{1} + \dots + w^{(l)}_{MN} a^{(l-1)}_{N}
    \end{bmatrix}
    %
    +
    \begin{bmatrix}
        b^{(l)}_{0} \\
        b^{(l)}_{1} \\
        \vdots \\
        b^{(l)}_{M}
    \end{bmatrix} \\
    %
    &=
    \begin{bmatrix}
        w^{(l)}_{00} a^{(l-1)}_{0} + w^{(l)}_{01} a^{(l-1)}_{1} + \dots + w^{(l)}_{0N} a^{(l-1)}_{N} + 1b^{(l)}_{0} \\
        w^{(l)}_{10} a^{(l-1)}_{0} + w^{(l)}_{11} a^{(l-1)}_{1} + \dots + w^{(l)}_{1N} a^{(l-1)}_{N} + 1b^{(l)}_{1} \\
        \vdots \\
        w^{(l)}_{M0} a^{(l-1)}_{0} + w^{(l)}_{M1} a^{(l-1)}_{1} + \dots + w^{(l)}_{MN} a^{(l-1)}_{N} + 1b^{(l)}_{M}
    \end{bmatrix} \\
    %
    &=
    \begin{bmatrix}
        w^{(l)}_{00} & w^{(l)}_{01} & \dots & w^{(l)}_{0N} & b^{(l)}_{0} \\
        w^{(l)}_{10} & w^{(l)}_{11} & \dots & w^{(l)}_{1N} & b^{(l)}_{1} \\
        \vdots & \vdots & & \vdots \\
        w^{(l)}_{M0} & w^{(l)}_{M1} & \dots & w^{(l)}_{MN} & b^{(l)}_{M}
    \end{bmatrix}
    %
    \begin{bmatrix}
        a^{(l-1)}_{0} \\
        a^{(l-1)}_{1} \\
        \vdots \\
        a^{(l-1)}_{N} \\
        1
    \end{bmatrix} \\
    %
    &=
    \begin{bmatrix}
        w^{(l)}_{00} & w^{(l)}_{01} & \dots & w^{(l)}_{0N} & w^{(l)}_{0(N+1)} \\
        w^{(l)}_{10} & w^{(l)}_{11} & \dots & w^{(l)}_{1N} & w^{(l)}_{1(N+1)} \\
        \vdots & \vdots & & \vdots \\
        w^{(l)}_{M0} & w^{(l)}_{M1} & \dots & w^{(l)}_{MN} & w^{(l)}_{M(N+1)}
    \end{bmatrix}
    %
    \begin{bmatrix}
        a^{(l-1)}_{0} \\
        a^{(l-1)}_{1} \\
        \vdots \\
        a^{(l-1)}_{N} \\
        a^{(l-1)}_{N+1}
    \end{bmatrix} \\
    %
    &= 
    W^{(l)} \, a^{l-1}
\end{align*}
$$

- For instante, we fix $l=2$ (that is last layer $L$), therefore we want compute between last layer and middle layer:

$$
\begin{align*}
    z^{(l)} &= W^{(l)} \, a^{l-1} \\
    &= W^{(2)} \, a^{1} \\
    &=
    \begin{bmatrix}
        w^{(2)}_{00} & w^{(2)}_{01} & w^{(2)}_{02} & b^{(2)}_{0} \\
        w^{(2)}_{10} & w^{(2)}_{11} & w^{(2)}_{12} & b^{(2)}_{1}
    \end{bmatrix}
    %
    \begin{bmatrix}
        a^{(1)}_{0} \\
        a^{(1)}_{1} \\
        a^{(1)}_{2} \\
        1
    \end{bmatrix} \\
    % 
    &=
    \begin{bmatrix}
        w^{(2)}_{00} & w^{(2)}_{01} & w^{(2)}_{02} & w^{(2)}_{03} \\
        w^{(2)}_{10} & w^{(2)}_{11} & w^{(2)}_{12} & w^{(2)}_{13}
    \end{bmatrix}
    %
    \begin{bmatrix}
        a^{(1)}_{0} \\
        a^{(1)}_{1} \\
        a^{(1)}_{2} \\
        a^{(1)}_{3}
    \end{bmatrix} \\
    % 
    &=
    \begin{bmatrix}
        w^{(2)}_{00} a^{(1)}_{0} + w^{(2)}_{01} a^{(1)}_{1} + w^{(2)}_{02} a^{(1)}_{2} + w^{(2)}_{03} a^{(1)}_{3} \\
        w^{(2)}_{10} a^{(1)}_{0} + w^{(2)}_{11} a^{(1)}_{1} + w^{(2)}_{12} a^{(1)}_{2} + w^{(2)}_{13} a^{(1)}_{3}
    \end{bmatrix} \\
    %
    &=
    \begin{bmatrix}
        z^{(2)}_{0} \\
        z^{(2)}_{1}
    \end{bmatrix}
\end{align*}
$$

- For instante, we fix $l=1$, therefore we want compute between middle layer and input:

$$
\begin{align*}
    z^{(l)} &= W^{(l)} \, a^{l-1} \\
    &= W^{(1)} \, a^{0} \\
    &= W^{(1)} \, x \\  
    &=
    \begin{bmatrix}
        w^{(1)}_{00} & w^{(1)}_{01} & b^{(1)}_{0} \\
        w^{(1)}_{10} & w^{(1)}_{11} & b^{(1)}_{1} \\
        w^{(1)}_{20} & w^{(1)}_{21} & b^{(1)}_{2}
    \end{bmatrix}
    %
    \begin{bmatrix}
        x_{0} \\
        x_{1} \\
        1
    \end{bmatrix} \\
    %
    &=
    \begin{bmatrix}
        w^{(1)}_{00} & w^{(1)}_{01} & w^{(1)}_{02} \\
        w^{(1)}_{10} & w^{(1)}_{11} & w^{(1)}_{12} \\
        w^{(1)}_{20} & w^{(1)}_{21} & w^{(1)}_{22}
    \end{bmatrix}
    %
    \begin{bmatrix}
        x_{0} \\
        x_{1} \\
        x_{2}
    \end{bmatrix} \\
    %
    &=
    \begin{bmatrix}
        w^{(1)}_{00} x_{0} + w^{(1)}_{01} x_{1} + w^{(1)}_{02} x_{2} \\
        w^{(1)}_{10} x_{0} + w^{(1)}_{11} x_{1} + w^{(1)}_{12} x_{2} \\
        w^{(1)}_{20} x_{0} + w^{(1)}_{21} x_{1} + w^{(1)}_{22} x_{2}
    \end{bmatrix} \\
    %
    &=
    \begin{bmatrix}
        z^{(1)}_{0} \\
        z^{(1)}_{1} \\
        z^{(1)}_{2}
    \end{bmatrix}
\end{align*}
$$

Therefore, we understood that $b$ is just a weight that has always $1$ as input.

- In scalar form:
$$
\begin{align*}
    z^{(l)}_{i} &= \sum^{len(l)}_{i=0} \sum^{len(l-1)}_{j=0} w^{(l)}_{ij} \, a^{(l-1)}_{j} \\
\end{align*}
$$

$$
\begin{align*}
    z^{(2)}_{0} &= w^{(2)}_{00} a^{(1)}_{0} + w^{(2)}_{01} a^{(1)}_{1} + w^{(2)}_{02} a^{(1)}_{2} + w^{(2)}_{03} a^{(1)}_{3} \\
    z^{(2)}_{1} &= w^{(2)}_{10} a^{(1)}_{0} + w^{(2)}_{11} a^{(1)}_{1} + w^{(2)}_{12} a^{(1)}_{2} + w^{(2)}_{13} a^{(1)}_{3} \\
    \\
    z^{(1)}_{0} &= w^{(1)}_{00} x_{0} + w^{(1)}_{01} x_{1} + w^{(1)}_{02} x_{2} \\
    z^{(1)}_{1} &= w^{(1)}_{10} x_{0} + w^{(1)}_{11} x_{1} + w^{(1)}_{12} x_{2} \\
    z^{(1)}_{2} &= w^{(1)}_{20} x_{0} + w^{(1)}_{21} x_{1} + w^{(1)}_{22} x_{2}
\end{align*}
$$

In general:

$$
\begin{align*}
    \frac{\partial z^{(l)}_{i}}{\partial a^{(l-1)}_{j}} = w_{ij}^{(l)}
    \hspace{35pt}
    where
    \hspace{10pt}
    a^{(0)}_{j} = x_j
\end{align*}
$$

In specific case:

$l=2$

$$
\begin{align*}
    \frac{\partial z^{(2)}_{0}}{\partial a^{(1)}_{0}} = w_{00}^{(2)} &&&&
    \frac{\partial z^{(2)}_{0}}{\partial a^{(1)}_{1}} = w_{01}^{(2)} &&&&
    \frac{\partial z^{(2)}_{0}}{\partial a^{(1)}_{2}} = w_{02}^{(2)} &&&&
    \frac{\partial z^{(2)}_{0}}{\partial a^{(1)}_{3}} = w_{03}^{(2)} \\
    \\
    \frac{\partial z^{(2)}_{1}}{\partial a^{(1)}_{0}} = w_{10}^{(2)} &&&&
    \frac{\partial z^{(2)}_{1}}{\partial a^{(1)}_{1}} = w_{11}^{(2)} &&&&
    \frac{\partial z^{(2)}_{1}}{\partial a^{(1)}_{2}} = w_{12}^{(2)} &&&&
    \frac{\partial z^{(2)}_{1}}{\partial a^{(1)}_{3}} = w_{13}^{(2)}
\end{align*}
$$

$l=1$

$$
\begin{align*}
    \frac{\partial z^{(1)}_{0}}{\partial a^{(1)}_{0}} = \frac{\partial z^{(1)}_{0}}{\partial x_{0}} = w_{00}^{(1)} &&&&
    \frac{\partial z^{(1)}_{0}}{\partial a^{(1)}_{1}} = \frac{\partial z^{(1)}_{0}}{\partial x_{1}} = w_{01}^{(1)} &&&&
    \frac{\partial z^{(1)}_{0}}{\partial a^{(1)}_{2}} = \frac{\partial z^{(1)}_{0}}{\partial x_{2}} = w_{02}^{(1)} \\
    \\
    \frac{\partial z^{(1)}_{1}}{\partial a^{(1)}_{0}} = \frac{\partial z^{(1)}_{1}}{\partial x_{0}} = w_{10}^{(1)} &&&&
    \frac{\partial z^{(1)}_{1}}{\partial a^{(1)}_{1}} = \frac{\partial z^{(1)}_{1}}{\partial x_{1}} = w_{11}^{(1)} &&&&
    \frac{\partial z^{(1)}_{1}}{\partial a^{(1)}_{2}} = \frac{\partial z^{(1)}_{1}}{\partial x_{2}} = w_{12}^{(1)} \\
    \\
    \frac{\partial z^{(1)}_{2}}{\partial a^{(1)}_{0}} = \frac{\partial z^{(1)}_{2}}{\partial x_{0}} = w_{20}^{(1)} &&&&
    \frac{\partial z^{(1)}_{2}}{\partial a^{(1)}_{1}} = \frac{\partial z^{(1)}_{2}}{\partial x_{1}} = w_{21}^{(1)} &&&&
    \frac{\partial z^{(1)}_{2}}{\partial a^{(1)}_{2}} = \frac{\partial z^{(1)}_{2}}{\partial x_{2}} = w_{22}^{(1)}
\end{align*}
$$

In general:

$$
\begin{align*}
    \frac{\partial z^{(l)}_{i}}{\partial w^{(l)}_{ij}} = a^{(l-1)}_{j}
    \hspace{35pt}
    where
    \hspace{10pt}
    a^{(0)}_{j} = x_j
\end{align*}
$$

In specific case:

$l=2$

$$
\begin{align*}
    \frac{\partial z^{(2)}_{0}}{\partial w_{00}^{(2)}} = a^{(1)}_{0} &&&&
    \frac{\partial z^{(2)}_{0}}{\partial w_{01}^{(2)}} = a^{(1)}_{1} &&&&
    \frac{\partial z^{(2)}_{0}}{\partial w_{02}^{(2)}} = a^{(1)}_{2} &&&&
    \frac{\partial z^{(2)}_{0}}{\partial w_{03}^{(2)}} = a^{(1)}_{3} 
    \\
    \frac{\partial z^{(2)}_{1}}{\partial w_{10}^{(2)}} = a^{(1)}_{0} &&&&
    \frac{\partial z^{(2)}_{1}}{\partial w_{11}^{(2)}} = a^{(1)}_{1} &&&&
    \frac{\partial z^{(2)}_{1}}{\partial w_{12}^{(2)}} = a^{(1)}_{2} &&&&
    \frac{\partial z^{(2)}_{1}}{\partial w_{13}^{(2)}} = a^{(1)}_{3}
\end{align*}
$$

$l=2$

$$
\begin{align*}
    \frac{\partial z^{(1)}_{0}}{\partial w_{00}^{(1)}} = a^{(1)}_{0} = x_{0} &&&&
    \frac{\partial z^{(1)}_{0}}{\partial w_{01}^{(1)}} = a^{(1)}_{1} = x_{1} &&&&
    \frac{\partial z^{(1)}_{0}}{\partial w_{02}^{(1)}} = a^{(1)}_{2} = x_{2} \\
    \\
    \frac{\partial z^{(1)}_{1}}{\partial w_{10}^{(1)}} = a^{(1)}_{0} = x_{0} &&&&
    \frac{\partial z^{(1)}_{1}}{\partial w_{11}^{(1)}} = a^{(1)}_{1} = x_{1} &&&&
    \frac{\partial z^{(1)}_{1}}{\partial w_{12}^{(1)}} = a^{(1)}_{2} = x_{2} \\
    \\
    \frac{\partial z^{(1)}_{2}}{\partial w_{20}^{(1)}} = a^{(1)}_{0} = x_{0} &&&&
    \frac{\partial z^{(1)}_{2}}{\partial w_{21}^{(1)}} = a^{(1)}_{1} = x_{1} &&&&
    \frac{\partial z^{(1)}_{2}}{\partial w_{22}^{(2)}} = a^{(1)}_{2} = x_{2}
\end{align*}
$$

Activation function:
$$
\begin{align*}
    a^{(l)}_{i} = \frac{1}{1 + e^{-z^{(l)}_{i}}} \\
\end{align*}
$$

In general:

$$
\begin{align*}
    \frac{\partial a^{(l)}_{i}}{\partial z^{(l)}_{i}} = a^{(l)}_{i} (1 - a^{(l)}_{i})
    \hspace{35pt}
    where
    \hspace{10pt}
    1 \le l < L
\end{align*}
$$

Note that for $L=2$ we have linear activation that we compute in a different way, as we have already seen before. But for the hidden layer we have the no linear activation functions.

Update weights for $l=2$:
$$
\begin{align*}
    \frac{\partial MSE}{\partial w^{(2)}_{00}} = 
    \frac{\partial MSE}{\partial y^{(2)}_{0}} \,
    \frac{\partial y^{(2)}_{0}}{\partial z^{(2)}_{0}} \,
    \frac{\partial z^{(2)}_{0}}{\partial w^{(2)}_{00}} &&&&
    \frac{\partial MSE}{\partial w^{(2)}_{01}} = 
    \frac{\partial MSE}{\partial y^{(2)}_{0}} \,
    \frac{\partial y^{(2)}_{0}}{\partial z^{(2)}_{0}} \,
    \frac{\partial z^{(2)}_{0}}{\partial w^{(2)}_{01}} &&&&
    \frac{\partial MSE}{\partial w^{(2)}_{02}} = 
    \frac{\partial MSE}{\partial y^{(2)}_{0}} \,
    \frac{\partial y^{(2)}_{0}}{\partial z^{(2)}_{0}} \,
    \frac{\partial z^{(2)}_{0}}{\partial w^{(2)}_{02}} &&&&
    \frac{\partial MSE}{\partial w^{(2)}_{03}} = 
    \frac{\partial MSE}{\partial y^{(2)}_{0}} \,
    \frac{\partial y^{(2)}_{0}}{\partial z^{(2)}_{0}} \,
    \frac{\partial z^{(2)}_{0}}{\partial w^{(2)}_{03}}
\end{align*}
$$

$$
\begin{align*}
    \frac{\partial MSE}{\partial w^{(2)}_{10}} = 
    \frac{\partial MSE}{\partial y^{(2)}_{1}} \,
    \frac{\partial y^{(2)}_{1}}{\partial z^{(2)}_{1}} \,
    \frac{\partial z^{(2)}_{1}}{\partial w^{(2)}_{10}} &&&&
    \frac{\partial MSE}{\partial w^{(2)}_{11}} = 
    \frac{\partial MSE}{\partial y^{(2)}_{1}} \,
    \frac{\partial y^{(2)}_{1}}{\partial z^{(2)}_{1}} \,
    \frac{\partial z^{(2)}_{1}}{\partial w^{(2)}_{11}} &&&&
    \frac{\partial MSE}{\partial w^{(2)}_{12}} = 
    \frac{\partial MSE}{\partial y^{(2)}_{1}} \,
    \frac{\partial y^{(2)}_{1}}{\partial z^{(2)}_{1}} \,
    \frac{\partial z^{(2)}_{1}}{\partial w^{(2)}_{12}} &&&&
    \frac{\partial MSE}{\partial w^{(2)}_{13}} = 
    \frac{\partial MSE}{\partial y^{(2)}_{1}} \,
    \frac{\partial y^{(2)}_{1}}{\partial z^{(2)}_{1}} \,
    \frac{\partial z^{(2)}_{1}}{\partial w^{(2)}_{13}}
\end{align*}
$$

Update weights for $l=1$:
$$
\begin{align*}
    \frac{\partial MSE}{\partial w^{(1)}_{00}} &= 
    \frac{\partial MSE}{\partial y^{(2)}_{0}} \,
    \frac{\partial y^{(2)}_{0}}{\partial z^{(2)}_{0}} \, 
    \frac{\partial z^{(2)}_{0}}{\partial a^{(1)}_{0}} \,
    \frac{\partial a^{(1)}_{0}}{\partial z^{(1)}_{0}} \,
    \frac{\partial z^{(1)}_{0}}{\partial w^{(1)}_{00}} + &&&&&
    %
    \frac{\partial MSE}{\partial w^{(1)}_{01}} &= 
    \frac{\partial MSE}{\partial y^{(2)}_{0}} \,
    \frac{\partial y^{(2)}_{0}}{\partial z^{(2)}_{0}} \, 
    \frac{\partial z^{(2)}_{0}}{\partial a^{(1)}_{0}} \,
    \frac{\partial a^{(1)}_{0}}{\partial z^{(1)}_{0}} \,
    \frac{\partial z^{(1)}_{0}}{\partial w^{(1)}_{01}} + &&&&
    %
    \frac{\partial MSE}{\partial w^{(1)}_{02}} &= 
    \frac{\partial MSE}{\partial y^{(2)}_{0}} \,
    \frac{\partial y^{(2)}_{0}}{\partial z^{(2)}_{0}} \, 
    \frac{\partial z^{(2)}_{0}}{\partial a^{(1)}_{0}} \,
    \frac{\partial a^{(1)}_{0}}{\partial z^{(1)}_{0}} \,
    \frac{\partial z^{(1)}_{0}}{\partial w^{(1)}_{02}} + \\
    %
    &
    \frac{\partial MSE}{\partial y^{(2)}_{1}} \,
    \frac{\partial y^{(2)}_{1}}{\partial z^{(2)}_{1}} \, 
    \frac{\partial z^{(2)}_{1}}{\partial a^{(1)}_{0}} \,
    \frac{\partial a^{(1)}_{0}}{\partial z^{(1)}_{0}} \,
    \frac{\partial z^{(1)}_{0}}{\partial w^{(1)}_{00}} &&&&&
    %
    &
    \frac{\partial MSE}{\partial y^{(2)}_{1}} \,
    \frac{\partial y^{(2)}_{1}}{\partial z^{(2)}_{1}} \, 
    \frac{\partial z^{(2)}_{1}}{\partial a^{(1)}_{0}} \,
    \frac{\partial a^{(1)}_{0}}{\partial z^{(1)}_{0}} \,
    \frac{\partial z^{(1)}_{0}}{\partial w^{(1)}_{01}} &&&&
    %
    &
    \frac{\partial MSE}{\partial y^{(2)}_{1}} \,
    \frac{\partial y^{(2)}_{1}}{\partial z^{(2)}_{1}} \, 
    \frac{\partial z^{(2)}_{1}}{\partial a^{(1)}_{0}} \,
    \frac{\partial a^{(1)}_{0}}{\partial z^{(1)}_{0}} \,
    \frac{\partial z^{(1)}_{0}}{\partial w^{(1)}_{02}}
\end{align*}
$$


$$
\begin{align*}
    \frac{\partial MSE}{\partial w^{(1)}_{10}} &= 
    \frac{\partial MSE}{\partial y^{(2)}_{0}} \,
    \frac{\partial y^{(2)}_{0}}{\partial z^{(2)}_{0}} \, 
    \frac{\partial z^{(2)}_{0}}{\partial a^{(1)}_{1}} \,
    \frac{\partial a^{(1)}_{1}}{\partial z^{(1)}_{1}} \,
    \frac{\partial z^{(1)}_{1}}{\partial w^{(1)}_{10}} + &&&&&
    %
    \frac{\partial MSE}{\partial w^{(1)}_{11}} &= 
    \frac{\partial MSE}{\partial y^{(2)}_{0}} \,
    \frac{\partial y^{(2)}_{0}}{\partial z^{(2)}_{0}} \, 
    \frac{\partial z^{(2)}_{0}}{\partial a^{(1)}_{1}} \,
    \frac{\partial a^{(1)}_{1}}{\partial z^{(1)}_{1}} \,
    \frac{\partial z^{(1)}_{1}}{\partial w^{(1)}_{11}} + &&&&
    %
    \frac{\partial MSE}{\partial w^{(1)}_{12}} &= 
    \frac{\partial MSE}{\partial y^{(2)}_{0}} \,
    \frac{\partial y^{(2)}_{0}}{\partial z^{(2)}_{0}} \, 
    \frac{\partial z^{(2)}_{0}}{\partial a^{(1)}_{1}} \,
    \frac{\partial a^{(1)}_{1}}{\partial z^{(1)}_{1}} \,
    \frac{\partial z^{(1)}_{1}}{\partial w^{(1)}_{12}} + \\
    %
    &
    \frac{\partial MSE}{\partial y^{(2)}_{1}} \,
    \frac{\partial y^{(2)}_{1}}{\partial z^{(2)}_{1}} \, 
    \frac{\partial z^{(2)}_{1}}{\partial a^{(1)}_{1}} \,
    \frac{\partial a^{(1)}_{1}}{\partial z^{(1)}_{1}} \,
    \frac{\partial z^{(1)}_{1}}{\partial w^{(1)}_{10}} &&&&&
    %
    &
    \frac{\partial MSE}{\partial y^{(2)}_{1}} \,
    \frac{\partial y^{(2)}_{1}}{\partial z^{(2)}_{1}} \, 
    \frac{\partial z^{(2)}_{1}}{\partial a^{(1)}_{1}} \,
    \frac{\partial a^{(1)}_{1}}{\partial z^{(1)}_{1}} \,
    \frac{\partial z^{(1)}_{1}}{\partial w^{(1)}_{11}} &&&&
    %
    &
    \frac{\partial MSE}{\partial y^{(2)}_{1}} \,
    \frac{\partial y^{(2)}_{1}}{\partial z^{(2)}_{1}} \, 
    \frac{\partial z^{(2)}_{1}}{\partial a^{(1)}_{1}} \,
    \frac{\partial a^{(1)}_{1}}{\partial z^{(1)}_{1}} \,
    \frac{\partial z^{(1)}_{1}}{\partial w^{(1)}_{12}}
\end{align*}
$$


$$
\begin{align*}
    \frac{\partial MSE}{\partial w^{(1)}_{20}} &= 
    \frac{\partial MSE}{\partial y^{(2)}_{0}} \,
    \frac{\partial y^{(2)}_{0}}{\partial z^{(2)}_{0}} \, 
    \frac{\partial z^{(2)}_{0}}{\partial a^{(1)}_{2}} \,
    \frac{\partial a^{(1)}_{2}}{\partial z^{(1)}_{2}} \,
    \frac{\partial z^{(1)}_{2}}{\partial w^{(1)}_{10}} + &&&&&
    %
    \frac{\partial MSE}{\partial w^{(1)}_{21}} &= 
    \frac{\partial MSE}{\partial y^{(2)}_{0}} \,
    \frac{\partial y^{(2)}_{0}}{\partial z^{(2)}_{0}} \, 
    \frac{\partial z^{(2)}_{0}}{\partial a^{(1)}_{2}} \,
    \frac{\partial a^{(1)}_{2}}{\partial z^{(1)}_{2}} \,
    \frac{\partial z^{(1)}_{2}}{\partial w^{(1)}_{11}} + &&&&
    %
    \frac{\partial MSE}{\partial w^{(1)}_{22}} &= 
    \frac{\partial MSE}{\partial y^{(2)}_{0}} \,
    \frac{\partial y^{(2)}_{0}}{\partial z^{(2)}_{0}} \, 
    \frac{\partial z^{(2)}_{0}}{\partial a^{(1)}_{2}} \,
    \frac{\partial a^{(1)}_{2}}{\partial z^{(1)}_{2}} \,
    \frac{\partial z^{(1)}_{2}}{\partial w^{(1)}_{12}} + \\
    %
    &
    \frac{\partial MSE}{\partial y^{(2)}_{1}} \,
    \frac{\partial y^{(2)}_{1}}{\partial z^{(2)}_{1}} \, 
    \frac{\partial z^{(2)}_{1}}{\partial a^{(1)}_{2}} \,
    \frac{\partial a^{(1)}_{2}}{\partial z^{(1)}_{2}} \,
    \frac{\partial z^{(1)}_{2}}{\partial w^{(1)}_{20}} &&&&&
    % 
    &
    \frac{\partial MSE}{\partial y^{(2)}_{1}} \,
    \frac{\partial y^{(2)}_{1}}{\partial z^{(2)}_{1}} \, 
    \frac{\partial z^{(2)}_{1}}{\partial a^{(1)}_{2}} \,
    \frac{\partial a^{(1)}_{2}}{\partial z^{(1)}_{2}} \,
    \frac{\partial z^{(1)}_{2}}{\partial w^{(1)}_{21}} &&&&
    %
    &
    \frac{\partial MSE}{\partial y^{(2)}_{1}} \,
    \frac{\partial y^{(2)}_{1}}{\partial z^{(2)}_{1}} \, 
    \frac{\partial z^{(2)}_{1}}{\partial a^{(1)}_{2}} \,
    \frac{\partial a^{(1)}_{2}}{\partial z^{(1)}_{2}} \,
    \frac{\partial z^{(1)}_{2}}{\partial w^{(1)}_{22}}
\end{align*}
$$

Decompose

$$
\begin{align*}
    \delta^{(L)} &= \frac{\partial MSE}{\partial y} \,
    \frac{\partial y}{\partial z^{(L)}} \\
    &= 
    \frac{\partial MSE}{\partial a^{(L)}} \,
    \frac{\partial a^{(L)}}{\partial z^{(L)}} \\
\end{align*}
$$

$$
\begin{align*}
    \delta^{(L-1)} &= \delta^{(L)} \,
    \frac{\partial z^{(L)}}{\partial a^{(L-1)}} \,
    \frac{\partial a^{(L-1)}}{\partial z^{(L-1)}} \\
    %
    \delta^{(L-2)} &= \delta^{(L-1)} \,
    \frac{\partial z^{(L-1)}}{\partial a^{(L-2)}} \,
    \frac{\partial a^{(L-2)}}{\partial z^{(L-2)}} \\
    & \vdots \\
    \delta^{(l-1)} &= \delta^{(l)} \,
    \frac{\partial z^{(l)}}{\partial a^{(l-1)}} \,
    \frac{\partial a^{(l-1)}}{\partial z^{(l-1)}}
\end{align*}
$$

Therefore

$$
\begin{align*}
    \frac{\partial MSE}{\partial w^{(l)}_{ij}} = \delta^{(l)} \, \frac{\partial z^{(l)}}{\partial w^{(l)}_{ij}}
\end{align*}
$$

Scalar mode:

$$
\begin{align*}
    \delta^{(L)}_{i} &= 
    \frac{\partial MSE}{\partial a^{(L)}_{i}} \,
    \frac{\partial a^{(L)}_{i}}{\partial z^{(L)}_{i}}
    \hspace{75pt}
    where
    \hspace{10pt}
    0 \le i < len(L) \\
    %
    \delta^{(L-1)}_{k} &= 
    \sum^{len(L)}_{i=0} \delta^{(L)}_{i} \,
    \frac{\partial z^{(L)}_{i}}{\partial a^{(L-1)}_{k}} \,
    \frac{\partial a^{(L-1)}_{k}}{\partial z^{(L-1)}_{k}}
    \hspace{35pt}
    where
    \hspace{10pt}
    0 \le k < len(L-1) \\
    %
    &\vdots\\
    \delta^{(l-1)}_{k} &= 
    \sum^{len(l)}_{i=0} \delta^{(l)}_{i} \,
    \frac{\partial z^{(l)}_{i}}{\partial a^{(l-1)}_{k}} \,
    \frac{\partial a^{(l-1)}_{k}}{\partial z^{(l-1)}_{k}}
    \hspace{45pt}
    where
    \hspace{10pt}
    0 \le k < len(l-1)
\end{align*}
$$

Therefore:

$$
\begin{align*}
    \frac{\partial MSE}{\partial w^{(L)}_{ij}} &= \delta^{(L)}_{i} \, 
    \frac{\partial z^{(L)}_{i}}{\partial w^{(L)}_{ij}}
    \hspace{50pt}
    where
    \hspace{10pt}
    0 \le i < len(L) &
    0 \le j < len(L-1) \\
    %
    \frac{\partial MSE}{\partial w^{(L-1)}_{ij}} &= \delta^{(L-1)}_{i} \, 
    \frac{\partial z^{(L-1)}_{i}}{\partial w^{(L-1)}_{ij}}
    \hspace{35pt}
    where
    \hspace{10pt}
    0 \le i < len(L-1) &
    0 \le j < len(L-2) \\
    %
    & \vdots \\
    \frac{\partial MSE}{\partial w^{(l-1)}_{ij}} &= \delta^{(l-1)}_{i} \, 
    \frac{\partial z^{(l-1)}_{i}}{\partial w^{(l-1)}_{ij}}
    \hspace{40pt}
    where
    \hspace{10pt}
    0 \le i < len(l-1) &
    0 \le j < len(l-2)
\end{align*}
$$

## Implementation Step by Step

In [1]:
import numpy as np

np.random.seed(0)

### Forward pass

In [2]:
l1_size = 3
l2_size = 2

print("Input x:")
x = np.array([[1, 3]]).T
print(x, "\n")

print("Add 1 to input x:")
x = np.array([[1, 3, 1]]).T
print(x, "\n")

print("Layer 1:")
W_l1 = np.random.rand(l1_size, x.shape[0])
z_l1 = W_l1 @ x
a_l1 = 1 / (1 + np.exp(-z_l1))
a_l1 = np.vstack([a_l1, 1]) # add 1 input
print("W_l1", "\n", W_l1, "\n")
print("z_l1", "\n", z_l1, "\n")
print("a_l1", "\n", a_l1, "\n")

print("Layer 2:")
W_l2 = np.random.rand(l2_size, a_l1.shape[0])
z_l2 = W_l2 @ a_l1
print("W_l2", "\n", W_l2, "\n")
print("z_l2", "\n", z_l2, "\n")

y = z_l2
print("y", "\n", y, "\n")

t = np.random.randint(5, size=(2,1))
print("t" "\n", t, "\n")
MSE = 0.5 * ( (t[0] - y[0])** 2 + (t[1] - y[1])** 2 )
print("MSE", "\n", MSE, "\n")

Input x:
[[1]
 [3]] 

Add 1 to input x:
[[1]
 [3]
 [1]] 

Layer 1:
W_l1 
 [[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]] 

z_l1 
 [[3.29714498]
 [2.46174169]
 [4.07656897]] 

a_l1 
 [[0.96433074]
 [0.92141587]
 [0.98331745]
 [1.        ]] 

Layer 2:
W_l2 
 [[0.38344152 0.79172504 0.52889492 0.56804456]
 [0.92559664 0.07103606 0.0871293  0.0202184 ]] 

z_l2 
 [[2.18738862]
 [1.0639292 ]] 

y 
 [[2.18738862]
 [1.0639292 ]] 

t
 [[3]
 [0]] 

MSE 
 [0.89614129] 



### Backward pass

$$
\begin{align*}
    \delta^{(L)}_{i} &= 
    \frac{\partial MSE}{\partial a^{(L)}_{i}} \,
    \frac{\partial a^{(L)}_{i}}{\partial z^{(L)}_{i}}
    \hspace{35pt}
    where
    \hspace{10pt}
    0 \le i < len(L) \\
    %
    &= (y_i - t_i) \, 1 \\
    &= (y_i - t_i)
\end{align*}
$$

In [3]:
L2_size = y.shape[0]

delta_L2 = np.zeros(L2_size)
for i in range(L2_size):
    delta_L2[i] = y[i] - t[i]

print(f"Dimension of L2-layer: {L2_size}")
print(f"delta_L2: {delta_L2}")

Dimension of L2-layer: 2
delta_L2: [-0.81261138  1.0639292 ]


$$
\begin{align*}    
    \frac{\partial MSE}{\partial w^{(L)}_{ij}} &= \delta^{(L)}_{i} \, \frac{\partial z^{(L)}_{i}}{\partial w^{(L)}_{ij}}
    \hspace{35pt}
    where
    \hspace{10pt}
    0 \le i < len(L) &
    0 \le j < len(L-1) \\
    %
    &= \delta^{(L)}_{i} \, a^{(L-1)}_{j}
\end{align*}
$$

In [4]:
l1_size = a_l1.shape[0]

W_l2_grad = np.zeros_like(W_l2)
for i in range(L2_size):
    for j in range(l1_size):
        W_l2_grad[i,j] = delta_L2[i] * a_l1[j]

print("W_grad of layers 2:")
print(W_l2_grad)

W_grad of layers 2:
[[-0.78362613 -0.74875302 -0.79905495 -0.81261138]
 [ 1.02597963  0.98032125  1.04618015  1.0639292 ]]


 $$
\begin{align*}   
    \delta^{(L-1)}_{k} &= 
    \sum^{len(L)}_{i=0} \delta^{(L)}_{i} \,
    \frac{\partial z^{(L)}_{i}}{\partial a^{(L-1)}_{k}} \,
    \frac{\partial a^{(L-1)}_{k}}{\partial z^{(L-1)}_{k}}
    \hspace{35pt}
    where
    \hspace{10pt}
    0 \le k < len(L-1) \\
    %
    &= \sum^{len(L)}_{i=0} \delta^{(L)}_{i} \, w^{(L)}_{ik} \, a^{(L-1)}_{k} \, (1 - a^{(L-1)}_{k})
\end{align*}
$$

In [5]:
l1_size = z_l1.shape[0]

delta_l1 = np.zeros(l1_size)
for k in range(l1_size):
    acc = 0
    for i in range(L2_size):
        acc += delta_L2[i] * W_l2[i,k] * a_l1[k] * (1 - a_l1[k])
    delta_l1[k] = acc

print(f"Dimension of L1-layer: {l1_size}")
print(f"delta_L1: {delta_l1}")

Dimension of L1-layer: 3
delta_L1: [ 0.02315536 -0.04111273 -0.00552965]


$$
\begin{align*}
    \frac{\partial MSE}{\partial w^{(L-1)}_{ij}} &= \delta^{(L-1)}_{i} \,
    \frac{\partial z^{(L-1)}_{i}}{\partial w^{(L-1)}_{ij}}
    \hspace{35pt}
    where
    \hspace{10pt}
    0 \le i < len(L-1) &
    0 \le j < len(L-2) \\
    %
    &= \delta^{(L-1)}_{i} \, a^{(L-2)}_{j} \\
    &= \delta^{(L-1)}_{i} \, x_{j} \\
\end{align*}
$$

In [6]:
l0_size = x.shape[0]

W_l1_grad = np.zeros_like(W_l1)
for i in range(l1_size):
    for j in range(l0_size):
        W_l1_grad[i,j] = delta_l1[i] * x[j]

print("W_grad of layers 1:")
print(W_l1_grad)

W_grad of layers 1:
[[ 0.02315536  0.06946609  0.02315536]
 [-0.04111273 -0.12333819 -0.04111273]
 [-0.00552965 -0.01658895 -0.00552965]]


### Update weight

In [7]:
mu = 0.01

In [8]:
print("w_l1 before:")
print(W_l1)
W_l1 = W_l1 - mu * W_l1_grad

print("\n")

print("w_l1 new:")
print(W_l1)

w_l1 before:
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]


w_l1 new:
[[0.54858195 0.71449471 0.60253182]
 [0.54529431 0.42488818 0.64630524]
 [0.43764251 0.89193889 0.96371806]]


In [9]:
print("w_l2 before:")
print(W_l2)
W_l2 = W_l2 - mu * W_l2_grad

print("\n")

print("w_l2 new:")
print(W_l2)

w_l2 before:
[[0.38344152 0.79172504 0.52889492 0.56804456]
 [0.92559664 0.07103606 0.0871293  0.0202184 ]]


w_l2 new:
[[0.39127778 0.79921257 0.53688547 0.57617067]
 [0.91533684 0.06123285 0.0766675  0.00957911]]


In [10]:
print("BEFORE")
print("MSE", "\n", MSE, "\n")

x = np.array([[1,3]]).T
x = np.vstack([x, [1]])
z_l1 = W_l1 @ x
a_l1 = 1 / (1 + np.exp(-z_l1))
a_l1 = np.vstack([a_l1, 1]) # add 1 input
z_l2 = W_l2 @ a_l1
y = z_l2
MSE = 0.5 * ( (t[0] - y[0])** 2 + (t[1] - y[1])** 2 )

print("AFTER")
print("MSE", "\n", MSE, "\n")

BEFORE
MSE 
 [0.89614129] 

AFTER
MSE 
 [0.83001984] 



## Implementation of this Neural Network

In [11]:
import matplotlib.pyplot as plt
np.random.seed(2) #2

In [12]:
X = np.random.rand(1000, 2)
y = 15 * np.sin(X)

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
X_train.shape, y_train.shape

((670, 2), (670, 2))

In [15]:
in_size = 2
hid_1_size = 3
out_size = 2

sizes = [in_size, hid_1_size, out_size]

In [16]:
W = []

W.append(np.random.rand(sizes[1], sizes[0]+1))
print("W_l1 | Layer 1, with index 0")
print(W[0])

print("\n")

W.append(np.random.rand(sizes[2], sizes[1]+1))
print("W_l2 | Layer 2, with index 1")
print(W[1])

W_l1 | Layer 1, with index 0
[[0.68835318 0.2664969  0.86073305]
 [0.92287024 0.98690241 0.7362912 ]
 [0.23766617 0.81396055 0.21752617]]


W_l2 | Layer 2, with index 1
[[0.11588183 0.14899267 0.25292353 0.58446352]
 [0.81021254 0.25306758 0.55864633 0.88283835]]


In [17]:
z = []
a = []

# Layer 1, with index 0
z.append(np.zeros(sizes[1]))
a.append(np.zeros(sizes[1]))
print("z_l1 | Layer 1, with index 0:")
print(z[0])
print("a_l1 | Layer 1, with index 0:")
print(a[0])

print("\n")

# Layer 2, with index 1
z.append(np.zeros(sizes[2]))
a.append(np.zeros(sizes[2]))
print("z_l2 | Layer 2, with index 1:")
print(z[1])
print("a_l2 = y | Layer 2, with index 1:")
print(a[1])

z_l1 | Layer 1, with index 0:
[0. 0. 0.]
a_l1 | Layer 1, with index 0:
[0. 0. 0.]


z_l2 | Layer 2, with index 1:
[0. 0.]
a_l2 = y | Layer 2, with index 1:
[0. 0.]


In [18]:
def forward(x, log=False):

    if log: print("Input x:")
    x = np.array([x]).T
    if log: print(x, "\n")

    if log: print("Add 1 to input x:")
    x = np.vstack([x, 1])
    if log: print(x, "\n")

    if log: print("Layer 1:")
    z[0] = W[0] @ x
    a[0] = 1 / (1 + np.exp(-z[0]))
    a[0] = np.vstack([a[0], 1]) # add 1 input
    if log: print("W_l1", "\n", W[0], "\n")
    if log: print("z_l1", "\n", z[0], "\n")
    if log: print("a_l1", "\n", a[0], "\n")

    if log: print("Layer 2:")
    z[1] = W[1] @ a[0]
    a[1] = z[1]
    if log: print("W_l2", "\n", W[1], "\n")
    if log: print("z_l2", "\n", z[1], "\n")
    if log: print("y", "\n", a[1], "\n")

    return a[1]


def loss_MSE(xy, t, log=False):
    # MSE
    if log: print("t" "\n", t, "\n")

    try:
        MSE = 0.5 * ( (t[0] - y[0])** 2 + (t[1] - y[1])** 2 )
        return MSE
    except Exception as e:
        print(e)


def backward(t):

    # Initialization
    W_grad = []
    for w in W:
        W_grad.append(np.zeros_like(w))

    delta = []
    for i in range(1, len(sizes)):
        delta.append(np.zeros(sizes[i]))

    # -------------------------------
    # LAYER 2
    # compute delta
    for i in range(sizes[2]):
        delta[1][i] = a[1][i] - t[i]

    # compute W_grad
    for i in range(sizes[2]):
        for j in range(sizes[1]+1):
            W_grad[1][i,j] = delta[1][i] * a[0][j]

    # -------------------------------
    # LAYER 1
    # compute delta
    for k in range(sizes[1]):
        acc = 0
        for i in range(sizes[2]):
            acc += delta[1][i] * W[1][i,k] * a[0][k] * (1 - a[0][k])
        delta[0][k] = acc

    # compute W_grad
    for i in range(sizes[1]):
        for j in range(sizes[0]+1):
            W_grad[0][i,j] = delta[0][i] * x[j]

    # UPDATE WEIGHTS
    mu = 0.001
    for idx, w_grad in enumerate(W_grad):
        W[idx] = W[idx] - mu * w_grad

In [19]:
EPOCHS = 1000
for ep in range(EPOCHS):
    for i in range(X_train.shape[0]):
        target = y_train[i]
        out = forward(X_train[i])
        loss = loss_MSE(out, target)
        backward(target)

    if ep%100 == 0:
        loss = 0
        for j in range(X_train.shape[0]):
            target = y_train[j]
            out = forward(X_train[j])
            loss += loss_MSE(out, target)
        l_train = loss / X_train.shape[0]

        loss = 0
        for j in range(X_test.shape[0]):
            target = y_test[j]
            out = forward(X_test[j])
            loss += loss_MSE(out, target)
        l_test = loss / X_test.shape[0]

        print(f"Epoch: {ep}, \t Test loss: {l_test}, \t Train loss: {l_train}")

    # To visualize...
    # if ep%500 == 0:
    #     x_1 = X_test[:,0] + X_test[:,1]
    #     x_2 = y_test[:,0] + y_test[:,1]

    #     x_2_test = []
    #     for j in range(X_test.shape[0]):
    #         out = forward(X_test[j])
    #         x_2_test.append(out[0] + out[1])

    #     plt.plot(x_1, x_2)
    #     plt.plot(x_1, x_2_test)
    #     plt.show()

Epoch: 0, 	 Test loss: [12.99505228], 	 Train loss: [12.75279735]
Epoch: 100, 	 Test loss: [9.07089923], 	 Train loss: [9.21797802]
Epoch: 200, 	 Test loss: [6.86756914], 	 Train loss: [7.21262892]
Epoch: 300, 	 Test loss: [6.25708866], 	 Train loss: [6.6653543]
Epoch: 400, 	 Test loss: [6.11744927], 	 Train loss: [6.54977448]
Epoch: 500, 	 Test loss: [6.05963163], 	 Train loss: [6.49922852]
Epoch: 600, 	 Test loss: [6.00072049], 	 Train loss: [6.44633373]
Epoch: 700, 	 Test loss: [5.95762947], 	 Train loss: [6.41694092]
Epoch: 800, 	 Test loss: [5.93446773], 	 Train loss: [6.41081682]
Epoch: 900, 	 Test loss: [5.92651739], 	 Train loss: [6.41878687]


In [20]:
# Prediction
for i in range(5):
    out = forward(X_test[i])
    loss = loss_MSE(out, y_test[i])
    print(f"input \t{X_test[i][0]} {X_test[i][1]}")
    print(f"target \t{y_test[i][0]} {y_test[i][1]}")
    print(f"out \t{out[0][0]} {out[1][0]}")
    print(f"loss \t{loss} \n")

input 	0.7877663456138179 0.7242438157483649
target 	10.631690317464507 9.938538744701702
out 	5.886945494542504 9.318520184571856
loss 	[11.44851322] 

input 	0.15268904057496224 0.3869828259758974
target 	2.2814465179274093 5.660941159145452
out 	5.99201267580201 5.906997901068623
loss 	[6.91442257] 

input 	0.5250928301459313 0.12325240249941471
target 	7.519399959928136 1.8441087258028226
out 	6.807072301818691 1.8266540637971405
loss 	[0.25385768] 

input 	0.7608453487966739 0.5548347357241061
target 	10.343009071955935 7.9020425224062905
out 	6.193270334831237 7.258868767078659
loss 	[8.81700203] 

input 	0.43352297913889015 0.01953874317144122
target 	6.30105714315716 0.29306250002971485
out 	6.924505414029438 0.5552789842697301
loss 	[0.22872262] 

